
strategies:
  n_angular:
    enabled: false
  spatial:
    enabled: false
    min_gain: .0005
  #  min_gain: .002
    cache_time: 15


exchange:
  coinbase_pro:
    enabled: true
    websocket:
      depth: 10
      currency_pairs:
        - "BTC_USD"
        - "ETH_USD"
        - "LTC_USD"
        - "ETH_BTC"
    api:
      refresh_rate: 60
      credentials:
        api_key: "${env:COINBASEPRO_API_KEY}"
        secret_key: "${env:COINBASEPRO_SECRET_KEY}"
        passphrase: "${env:COINBASEPRO_PASSPHRASE}"
      funding:
  kraken:
    enabled: true
    websocket:
      depth: 10
      currency_pairs:
        - "BTC_USD"
        - "ETH_USD"
        - "LTC_USD"
        - "ETH_BTC"
    api:
      refresh_rate: 60
      credentials:
        api_key: "${env:KRAKEN_API_KEY}"
        secret_key: "${env:KRAKEN_SECRET_KEY}"
  bitfinex:
    enabled: false
    websocket:
      depth: 25 #1, 25, 100
      currency_pairs:
        - "BTC_USD"
        - "ETH_USD"
        - "LTC_USD"
        - "ETH_BTC"
    api:
      refresh_rate: 60
      credentials:
        api_key: "${env:BITFINEX_API_KEY}"
        secret_key: "${env:BITFINEX_SECRET_KEY}"
  gemini:
    enabled: true
    websocket:
      depth: 10
      currency_pairs:
        - "BTC_USD"
        - "ETH_USD"
        - "LTC_USD"
        - "ETH_BTC"
    api:
      refresh_rate: 60
      credentials:
        api_key: "${env:GEMINI_API_KEY}"
        secret_key: "${env:GEMINI_SECRET_KEY}"

